# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_BOX = "ubuntu/bionic64"

Vagrant.configure(2) do |config|
  config.vm.box = VM_BOX

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'docker'
    vb.memory = 4096
    vb.cpus = 2
#    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision :shell, path: "bootstrap-docker.sh"
#  config.vm.provision :docker

end
