# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Plugin required:
# vagrant plugin install vagrant-env
#
# If you want to use nfs under windows
# vagrant plugin install vagrant-winnfsd
#

require '../lib/utils.rb'


Vagrant.configure(2) do |config|
  config.env.enable # enable plugin

  USERNAME = ENV['USER']
  GH = ENV['GH']
  SSH_PUB_KEYS = ENV['SSH_PUB_KEYS']
  VM_BOX = ENV['VM_BOX']
  VM_NAME = ENV['VM_NAME']

  config.vm.box = VM_BOX
  config.vm.hostname = VM_NAME
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.171.10", name: "VirtualBox Host-Only Ethernet Adapter"
  config.vm.network "public_network", ip: "192.168.55.13", name: "Intel(R) I211 Gigabit Network Connection"
  config.vm.network "forwarded_port", guest: 3000, host: 15000, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 80, host: 15001, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8989, host: 8989, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 9117, host: 9117, protocol: "tcp"


  # config.vm.network "private_network", type: "dhcp" # already have one
  #nfs_under_windows(config.vm)

  config.vm.provider "virtualbox" do |vb|
    vb.name = VM_NAME
    vb.memory = 4096
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--vrde", "off"]
  end

  config.vm.provision "pkgs", type: "shell", path: "../scripts/pkgs.sh", before: "all", run: "once"

  config.vm.provision "users", type: "shell", path: "../scripts/users.sh",
    env: {"USERNAME" => USERNAME, "GH" => GH, "SSH_PUB_KEYS" => SSH_PUB_KEYS},
    privileged: true, run: "once", before: "all"

  config.vm.provision "user-environment", type: "shell", path: "../scripts/environment.sh",
    env: {"USERNAME" => USERNAME},
    privileged: true, run: "once"

  config.vm.provision "docker", type: "shell", path: "../scripts/bootstrap-docker.sh", env: {"USERNAME" => USERNAME}, run: "once"

end
