# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Plugin required:
# vagrant plugin install vagrant-env
#

Vagrant.configure(2) do |config|
  config.env.enable # enable plugin
  
  USERNAME = ENV['USER']
  GH = ENV['GH']
  SSH_PUB_KEYS = ENV['SSH_PUB_KEYS']
  VM_BOX = ENV['VM_BOX']
  VM_NAME = ENV['VM_NAME']

  config.vm.box = VM_BOX
  config.vm.provider "virtualbox" do |vb|
    vb.name = VM_NAME
    vb.memory = 4096
    vb.cpus = 2
#    vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--vrde", "off"]
  end

  # workaround for ubuntu 20.04
  config.vm.provision :shell, inline: "apt update && apt install -qy ansible"
  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "playbook.yaml"
  end

end
